// Code generated by MockGen. DO NOT EDIT.
// Source: photos.go

// Package mock_photos is a generated GoMock package.
package mock_photos

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	photos "github.com/twk/skeleton-go-api/internal/photos"
)

// Mockclient is a mock of client interface.
type Mockclient struct {
	ctrl     *gomock.Controller
	recorder *MockclientMockRecorder
}

// MockclientMockRecorder is the mock recorder for Mockclient.
type MockclientMockRecorder struct {
	mock *Mockclient
}

// NewMockclient creates a new mock instance.
func NewMockclient(ctrl *gomock.Controller) *Mockclient {
	mock := &Mockclient{ctrl: ctrl}
	mock.recorder = &MockclientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockclient) EXPECT() *MockclientMockRecorder {
	return m.recorder
}

// GetPhotos mocks base method.
func (m *Mockclient) GetPhotos(ctx context.Context, id int) (*photos.Photo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPhotos", ctx, id)
	ret0, _ := ret[0].(*photos.Photo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPhotos indicates an expected call of GetPhotos.
func (mr *MockclientMockRecorder) GetPhotos(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPhotos", reflect.TypeOf((*Mockclient)(nil).GetPhotos), ctx, id)
}
