// Code generated by MockGen. DO NOT EDIT.
// Source: request.go

// Package mock_client is a generated GoMock package.
package mock_client

import (
	context "context"
	io "io"
	http "net/http"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	logger "github.com/twk/skeleton-go-api/internal/logger"
)

// MockHTTPRequester is a mock of HTTPRequester interface.
type MockHTTPRequester struct {
	ctrl     *gomock.Controller
	recorder *MockHTTPRequesterMockRecorder
}

// MockHTTPRequesterMockRecorder is the mock recorder for MockHTTPRequester.
type MockHTTPRequesterMockRecorder struct {
	mock *MockHTTPRequester
}

// NewMockHTTPRequester creates a new mock instance.
func NewMockHTTPRequester(ctrl *gomock.Controller) *MockHTTPRequester {
	mock := &MockHTTPRequester{ctrl: ctrl}
	mock.recorder = &MockHTTPRequesterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHTTPRequester) EXPECT() *MockHTTPRequesterMockRecorder {
	return m.recorder
}

// Request mocks base method.
func (m *MockHTTPRequester) Request(ctx context.Context, logger *logger.Logger, method, url, path string, header, query map[string]string, body io.Reader) (*http.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Request", ctx, logger, method, url, path, header, query, body)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Request indicates an expected call of Request.
func (mr *MockHTTPRequesterMockRecorder) Request(ctx, logger, method, url, path, header, query, body interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Request", reflect.TypeOf((*MockHTTPRequester)(nil).Request), ctx, logger, method, url, path, header, query, body)
}
